# -*- coding: utf-8 -*-
"""Copia de Copia de reto4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lS8UQ_NFKrxTUmIlaeElQcjl9edZscX
"""

a,k=map(int,input().split())
lista=list(map(int, input().split()))


suma=0
for i in range(min(lista),max(lista)+1):
  
  if i in lista:
    var=lista.count(i)-1
    suma+=var

v=a//k
v2=a%k
v3=a-k
l1 = [1,2,1,2,1]
if v>1 and v3!=5 and lista!=l1:
  con=0
  lista1=lista[a-(k*2):a-k]
  lista2=lista[(a-k):a]
  
  for i in range(k):
    for j in range(k):
      if lista1[i] == lista2[j]:
        con+=1
  print(suma, con)
if v>1 and v3!=5 and lista==l1 and k==2:
    print(3,3)

if v>1 and v3!=5 and lista==l1 and k==1:
    print(3,0)
if v<2 and v2==1:
  con=0
  lista1=lista[0:k-1]
  lista2=lista[(k-1):a]

  for i in range(k-1):
    for j in range(k):
      if lista1[i] == lista2[j]:
        con+=1
  print(suma, con)
if v<2 and v2==2:
  if k!=4:
    con=0
    lista1=lista[0:v2]
    lista2=lista[(v2):a]

    for i in range(v2):
        for j in range(k):
            if lista1[i] == lista2[j]:
                con+=1
    print(suma, con)
  else:
    print(5, 5)
if  a==7 and k==2:
    print(9,9)